### ISSUE TITLE
`yarn dev` and `yarn build` both fail

### ISSUE THREAD

**Issue by gamer191** [cfw-guide/ios.cfw.guide#257]
I followed the instructions in the Readme, but both `yarn dev` and `yarn build` are failing. I'm wondering if I did anything wrong?
```bash
jay@Ubuntu11:~/PycharmProjects/ios.cfw.guide$ yarn dev
yarn run v1.22.21
$ vuepress dev docs
warning an anonymous plugin or theme was detected and ignored
info Initializing VuePress and preparing data...
error error in hook onInitialized from vuepress-dynamic-pages
Error: File '/home/jay/PycharmProjects/ios.cfw.guide/docs/en_US/include/using-Cydia.md' not found.
    at _replaceIncludeByContent (/home/jay/PycharmProjects/ios.cfw.guide/node_modules/markdown-it-include/dist/markdownItInclude.js:90:17)
    at Array._includeFileParts (/home/jay/PycharmProjects/ios.cfw.guide/node_modules/markdown-it-include/dist/markdownItInclude.js:122:17)
    at Core.process (/home/jay/PycharmProjects/ios.cfw.guide/node_modules/markdown-it/lib/parser_core.js:54:13)
    at MarkdownIt.parse (/home/jay/PycharmProjects/ios.cfw.guide/node_modules/markdown-it/lib/index.js:524:13)
    at MarkdownIt.render (/home/jay/PycharmProjects/ios.cfw.guide/node_modules/markdown-it/lib/index.js:544:36)
    at md.render (/home/jay/PycharmProjects/ios.cfw.guide/node_modules/@mdit-vue/plugin-headers/dist/index.cjs:21:20)
    at md.render (/home/jay/PycharmProjects/ios.cfw.guide/node_modules/@mdit-vue/plugin-title/dist/index.cjs:23:20)
    at md.render (/home/jay/PycharmProjects/ios.cfw.guide/node_modules/@mdit-vue/plugin-frontmatter/dist/index.cjs:20:12)
    at renderPageContent (/home/jay/PycharmProjects/ios.cfw.guide/node_modules/@vuepress/core/lib/page/renderPageContent.js:14:42)
    at createPage (/home/jay/PycharmProjects/ios.cfw.guide/node_modules/@vuepress/core/lib/page/createPage.js:29:144)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

```
jay@Ubuntu11:~/PycharmProjects/ios.cfw.guide$ yarn build
yarn run v1.22.21
$ vuepress build docs
warning an anonymous plugin or theme was detected and ignored
info Initializing VuePress and preparing data...
error error in hook onInitialized from vuepress-dynamic-pages
Error: File '/home/jay/PycharmProjects/ios.cfw.guide/docs/en_US/include/using-Cydia.md' not found.
    at _replaceIncludeByContent (/home/jay/PycharmProjects/ios.cfw.guide/node_modules/markdown-it-include/dist/markdownItInclude.js:90:17)
    at Array._includeFileParts (/home/jay/PycharmProjects/ios.cfw.guide/node_modules/markdown-it-include/dist/markdownItInclude.js:122:17)
    at Core.process (/home/jay/PycharmProjects/ios.cfw.guide/node_modules/markdown-it/lib/parser_core.js:54:13)
    at MarkdownIt.parse (/home/jay/PycharmProjects/ios.cfw.guide/node_modules/markdown-it/lib/index.js:524:13)
    at MarkdownIt.render (/home/jay/PycharmProjects/ios.cfw.guide/node_modules/markdown-it/lib/index.js:544:36)
    at md.render (/home/jay/PycharmProjects/ios.cfw.guide/node_modules/@mdit-vue/plugin-headers/dist/index.cjs:21:20)
    at md.render (/home/jay/PycharmProjects/ios.cfw.guide/node_modules/@mdit-vue/plugin-title/dist/index.cjs:23:20)
    at md.render (/home/jay/PycharmProjects/ios.cfw.guide/node_modules/@mdit-vue/plugin-frontmatter/dist/index.cjs:20:12)
    at renderPageContent (/home/jay/PycharmProjects/ios.cfw.guide/node_modules/@vuepress/core/lib/page/renderPageContent.js:14:42)
    at createPage (/home/jay/PycharmProjects/ios.cfw.guide/node_modules/@vuepress/core/lib/page/createPage.js:29:144)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**Comment by gamer191** [comment]
After running some Github actions tests (at https://github.com/gamer191/ios.cfw.guide/), it appears that it builds on MacOS, but not on Linux. The workflow was switched to MacOS in https://github.com/cfw-guide/ios.cfw.guide/commit/dbe65f38d8327477587ca83ac77b01397b91de3b, but I'm not sure why :thinking:

**Comment by gamer191** [comment]
After running another test (https://github.com/gamer191/ios.cfw.guide/actions/runs/7230345594), it appears that `build` works on Windows and MacOS, but fails on Linux, as the log above demonstrates

`ghbuild` also fails on Windows, due to an unrelated issue
